server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/finflow
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

app.jwt.secret=ZmluZmxvdy1zZWNyZXQta2V5LWZvci1kZXZlbG9wbWVudC1vbmx5LTEyMw==
app.jwt.expiration-ms=86400000

logging.level.com.financetracker=DEBUG
logging.level.org.springframework.security=INFO

app.cors.allowed-origins=http://localhost:3000

spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.date-format=yyyy-MM-dd

spring.security.oauth2.client.registration.google.client-id= 700686367338-gcc1ih0dgt7tdl9c2j6fgr2kpqb0q3k9.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=spring.security.oauth2.client.registration.google.client-id= 700686367338-gcc1ih0dgt7tdl9c2j6fgr2kpqb0q3k9.apps.googleusercontent.com

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=abhivanshparashar@gmail.com
spring.mail.password=plbnkknqiipenjki

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.frontend-url=http://localhost:3000